module.exports = {
  "BASE": "https://www.o-home.com/public/v3/views/wap/page/dressUp/img/",
  "imageList": [
    'loading.png',
    'logo.png',
    'btn.png',
    'qrcode.jpg',
    'item-class.png',
    'role1.png',
    'role2.png',
    'title.png',
    'title2.png',
    'sex.png',
    'share.png',
  ],
  "bgs": [
    "bg/bg-1.png",
    "bg/bg-2.png",
    "bg/bg-3.png",
    "bg/bg-4.png",
    "bg/bg-5.png",
    "bg/bg-6.png",
    "bg/bg-7.png",
    "bg/bg-8.png",
    "bg/bg-9.png",
    "bg/bg-10.png",
    "bg/bg-11.png",
  ],
  "gifts": [
    'gift-1.png',
    'gift-2.png',
    'gift-3.png',
    'gift-4.png',
    'gift-5.png',
    'gift-6.png',
    'gift-7.png',
    'gift-8.png',
    'prize_btn.png',
  ],
}
