var _module$exports;

function _defineProperty(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, {
            value: value,
            enumerable: true,
            configurable: true,
            writable: true
        });
    } else {
        obj[key] = value;
    }
    return obj;
}

module.exports = (_module$exports = {
    urlNotInDomainList: "不在request合法域名列表中，请到微信公众号平台-登录小程序账户密码-进入小程序后台-开发-开发设置-服务器域名",
    requestFailTimeout: "请求超时",
    caozuochenggong: "操作成功",
    chakanzuoping: "查看作品",
    xitongguanggao: "系统广告",
    an: "按",
    tao: "套",
    zhuangxiugongdi: "装修工地",
    ge: "个",
    xiaoqu: "小区",
    gegongdi: "个工地",
    jieduan: "阶段",
    fangxing: "房型",
    myxggd: "没有相关工地",
    mygdl: "没有更多了",
    shangpingshoucang: "商品收藏",
    tupianshoucang: "图片收藏",
    gongdishoucang: "工地收藏",
    chanpingshoucang: "产品收藏",
    quanjingtushoucang: "全景图收藏",
    wodedingdan: "我的订单",
    wodedizhi: "我的地址",
    wodeyouhuiquan: "我的优惠券",
    wodeyuyue: "我的预约",
    lianxikefu: "联系客服",
    qingchuhuancun: "清除缓存",
    taotu: "套图",
    dantu: "单图",
    quanjingtu: "全景图",
    shousuo: "搜索",
    zonghepaixu: "综合排序",
    buxian: "不限",
    anshoucangliang: "按收藏量",
    anliulanliang: "按浏览量",
    liulan: "浏览",
    gengduo: "更多",
    shangpingsousuo: "商品搜索",
    remenxuangou: "热门选购",
    quxiao: "取消",
    shewei: "设为",
    tianjiadizhi: "添加地址",
    daoruweixindizhi: "导入微信地址",
    xingming: "姓名",
    shoujihao: "手机号",
    diqu: "地区",
    qingxuanzediqu: "请选择地区",
    xiangxidizhi: "详细地址",
    sheweimoren: "设为默认",
    baocunxiugai: "保存修改",
    hqzxgj: "获取装修报价",
    fxwxhy: "分享微信好友",
    ndzxys: "你的装修预算",
    yuan: "元",
    srfwmj: "请输入房屋面积",
    shuruhaoma: "输入号码,报价自动发送",
    huoqushoujihao: "获取手机号",
    lijijisuan: "立即计算",
    txxxhqmffuwu: "填写信息获取免费服务,定制更精准预算规划",
    yixuan: "已选",
    zanwugaishu: "暂无概述",
    zanwucanshu: "暂无参数",
    yi: "已",
    shoucang: "收藏",
    gouwuche: "购物车",
    jiarugouwuche: "加入购物车",
    lijigoumai: "立即购买",
    guanbi: "关闭",
    renzheng: "认证",
    anli: "案例",
    gongdi: "工地",
    tesefuwu: "特色服务",
    zhuangxiuanli: "装修案例",
    gong: "共",
    shejituandui: "设计团队",
    ren: "人",
    nian: "年经验",
    gongyizhanshi: "工艺展示"
}, _defineProperty(_module$exports, "gengduo", "更多"), _defineProperty(_module$exports, "shigongtuandui", "施工团队"), 
_defineProperty(_module$exports, "shangjiaxinxi", "商家信息"), _defineProperty(_module$exports, "chengjieleixing", "承接类型"), 
_defineProperty(_module$exports, "zwszcjlx", "暂未设置承接类型"), _defineProperty(_module$exports, "chengjiejiawei", "承接价位"), 
_defineProperty(_module$exports, "zwszcjjw", "暂未设置承接价位"), _defineProperty(_module$exports, "fuwuquyu", "服务区域"), 
_defineProperty(_module$exports, "zwszfwq", "暂未设置服务区域"), _defineProperty(_module$exports, "shiyong", "使用"), 
_defineProperty(_module$exports, "qushiyong", "去使用"), _defineProperty(_module$exports, "weishengxiao", "未生效"), 
_defineProperty(_module$exports, "bsyyhq", "不使用优惠券"), _defineProperty(_module$exports, "yilingqu", "已领取"), 
_defineProperty(_module$exports, "lingqu", "领取"), _defineProperty(_module$exports, "yilingwan", "已领完"), 
_defineProperty(_module$exports, "dangquanxuanze", "当前选择"), _defineProperty(_module$exports, "qsrzxgsmc", "请输入装修公司名称"), 
_defineProperty(_module$exports, "shuaixuan", "筛选"), _defineProperty(_module$exports, "xingyong", "信用"), 
_defineProperty(_module$exports, "jvli", "距离"), _defineProperty(_module$exports, "zonghe", "综合"), 
_defineProperty(_module$exports, "quyu", "区域"), _defineProperty(_module$exports, "quanbu", "全部"), 
_defineProperty(_module$exports, "leixing", "类型"), _defineProperty(_module$exports, "fengge", "风格"), 
_defineProperty(_module$exports, "yusuan", "预算"), _defineProperty(_module$exports, "qingkong", "清空"), 
_defineProperty(_module$exports, "queren", "确认"), _defineProperty(_module$exports, "quan", "券"), 
_defineProperty(_module$exports, "cu", "促"), _defineProperty(_module$exports, "wang", "万"), 
_defineProperty(_module$exports, "weiguanfenxi", "围观粉丝"), _defineProperty(_module$exports, "shigongliucheng", "施工流程"), 
_defineProperty(_module$exports, "quxiaoshoucang", "取消收藏"), _defineProperty(_module$exports, "nindexingming", "您的姓名"), 
_defineProperty(_module$exports, "nindedianhua", "您的电话"), _defineProperty(_module$exports, "mindeneirong", "您的内容"), 
_defineProperty(_module$exports, "zaixianliuyan", "在线留言"), _defineProperty(_module$exports, "xyndsq", "需要您的授权"), 
_defineProperty(_module$exports, "wltgghdfw", "为了提供更好的服务"), _defineProperty(_module$exports, "qzshdtskzdjyx", "请在稍后的提示框中点击“允许”"), 
_defineProperty(_module$exports, "wozhidaole", "我知道了"), _defineProperty(_module$exports, "myxgxx", "没有相关信息"), 
_defineProperty(_module$exports, "dianhuazixun", "电话咨询"), _defineProperty(_module$exports, "zuopinganli", "作品案例"), 
_defineProperty(_module$exports, "qxzdz", "请选择地址"), _defineProperty(_module$exports, "qxzyhq", "请选择优惠券"), 
_defineProperty(_module$exports, "youhuiquan", "优惠券"), _defineProperty(_module$exports, "weixuanze", "未选择"), 
_defineProperty(_module$exports, "shangpingheji", "商品合计"), _defineProperty(_module$exports, "youhui", "优惠"), 
_defineProperty(_module$exports, "lijixiadan", "立即下单"), _defineProperty(_module$exports, "lijizhifu", "立即支付"), 
_defineProperty(_module$exports, "dingdanhao", "订单号"), _defineProperty(_module$exports, "chuangjianshijian", "创建时间"), 
_defineProperty(_module$exports, "syyhq", "使用优惠券"), _defineProperty(_module$exports, "youhuijinge", "优惠金额"), 
_defineProperty(_module$exports, "zhifue", "支付额"), _defineProperty(_module$exports, "fenxianghaoyou", "分享好友"), 
_defineProperty(_module$exports, "weixinhaoyou", "微信好友"), _defineProperty(_module$exports, "fenxianghaibao", "分享海报"), 
_defineProperty(_module$exports, "baocunhaibao", "保存海报"), _defineProperty(_module$exports, "qushouquan", "去授权"), 
_defineProperty(_module$exports, "yuyuejinge", "预约金额"), _defineProperty(_module$exports, "mashangyuyue", "马上预约"), 
_defineProperty(_module$exports, "sousuo", "搜索"), _defineProperty(_module$exports, "myxgtp", "没有相关图片"), 
_defineProperty(_module$exports, "tijiao", "提交"), _defineProperty(_module$exports, "zhifujinge", "支付金额"), 
_defineProperty(_module$exports, "mpmzxygj", "毛坯房装修预估价"), _defineProperty(_module$exports, "wanyuan", "万元"), 
_defineProperty(_module$exports, "xhzxgjjhdnmfzx", "稍后装修管家将回电您,免费提供装修咨询服务"), _defineProperty(_module$exports, "yclppjgclbtwz", "因材料品牌及工程量不同,具体报价以量房实测为准"), 
_defineProperty(_module$exports, "wsyxxx", "完善以下信息"), _defineProperty(_module$exports, "rwmgljndjtxqyxfw", "让我们更了解您的具体需求,优先为您服务"), 
_defineProperty(_module$exports, "njdzxlxs", "您家的装修类型是"), _defineProperty(_module$exports, "jiazhuang", "家装"), 
_defineProperty(_module$exports, "gongzhuang", "公装"), _defineProperty(_module$exports, "bangongshi", "办公室"), 
_defineProperty(_module$exports, "cantingdeng", "餐厅等"), _defineProperty(_module$exports, "njdfwzts", "您家的房屋状态是"), 
_defineProperty(_module$exports, "esffxfy", "二手翻新会比毛坯房多部分分拆改费用"), _defineProperty(_module$exports, "maopeifang", "毛坯房"), 
_defineProperty(_module$exports, "jiufangfanxin", "旧房翻新"), _defineProperty(_module$exports, "jvbugaizao", "局部改造"), 
_defineProperty(_module$exports, "njzbssshkszx", "您家准备什么时候开始装修"), _defineProperty(_module$exports, "bangeyuenei", "半个月内"), 
_defineProperty(_module$exports, "yigeyuenei", "一个月内"), _defineProperty(_module$exports, "lianggeyuenei", "两个月内"), 
_defineProperty(_module$exports, "linaggeyueyishang", "两个月以上"), _defineProperty(_module$exports, "ninjiadeloupan", "您家的楼盘"), 
_defineProperty(_module$exports, "txlpxxwnyzsg", "填写楼盘信息,将为您家附近的优质施工方"), _defineProperty(_module$exports, "qsrnjdlp", "请输入您家的楼盘、小区"), 
_defineProperty(_module$exports, "lijitijiao", "立即提交"), _defineProperty(_module$exports, "xiangshangping", "项商品"), 
_defineProperty(_module$exports, "qufukuan", "去付款"), _defineProperty(_module$exports, "dianhua", "电话"), 
_defineProperty(_module$exports, "meiyouxinxi", "没有信息"), _defineProperty(_module$exports, "shouye", "首页"), 
_defineProperty(_module$exports, "fenlei", "分类"), _defineProperty(_module$exports, "gouwuche", "购物车"), 
_defineProperty(_module$exports, "dqxtpzcc", "读取系统配置出错！"), _defineProperty(_module$exports, "nhdwsskb", "您好，我可以带你快速跳转页面，点我试试看吧！"), 
_defineProperty(_module$exports, "yifuzhi", "已复制"), _defineProperty(_module$exports, "zhaobudaoidw", "找不到ID为"), 
_defineProperty(_module$exports, "yzxcx", "预置小程序"), _defineProperty(_module$exports, "dyzxcx", "的预置小程序"), 
_defineProperty(_module$exports, "dappidwx", "的appID无效"), _defineProperty(_module$exports, "dappidbz", "的appID不在配置列表中"), 
_defineProperty(_module$exports, "zbdym", "找不到页面"), _defineProperty(_module$exports, "wzdz", "未知动作"), 
_defineProperty(_module$exports, "zanwu", "暂无"), _defineProperty(_module$exports, "qxqqwsz", "权限，请前往设置开启"), 
_defineProperty(_module$exports, "qwsz", "前往设置"), _defineProperty(_module$exports, "kucun", "库存"), 
_defineProperty(_module$exports, "gmsl", "购买数量"), _defineProperty(_module$exports, "qclsjl", "清除历史纪录"), 
_defineProperty(_module$exports, "jiesuan", "结算"), _defineProperty(_module$exports, "gwckkry", "购物车空空如也~"), 
_defineProperty(_module$exports, "msgg", "马上逛逛"), _defineProperty(_module$exports, "daifukuan", "待付款"), 
_defineProperty(_module$exports, "daifahuo", "待发货"), _defineProperty(_module$exports, "daishouhuo", "待收货"), 
_defineProperty(_module$exports, "yiwancheng", "已完成"), _defineProperty(_module$exports, "yituikuan", "已退款"), 
_defineProperty(_module$exports, "myclddo", "还没有此类订单哦~"), _defineProperty(_module$exports, "chongshi", "重试"), 
_defineProperty(_module$exports, "mykydyhq", "没有可用的优惠券"), _defineProperty(_module$exports, "weishiyong", "未使用"), 
_defineProperty(_module$exports, "yishixiao", "已失效"), _defineProperty(_module$exports, "nhmyclyhq", "您还没有此类优惠券"), 
_defineProperty(_module$exports, "tjbf", "条件不符"), _defineProperty(_module$exports, "yishiyong", "已使用"), 
_defineProperty(_module$exports, "yiguoqi", "已过期"), _defineProperty(_module$exports, "nhmyscgspo", "您还没有收藏过商品哦"), 
_defineProperty(_module$exports, "hsygg", "回首页逛逛"), _defineProperty(_module$exports, "canshu", "参数"), 
_defineProperty(_module$exports, "gaishu", "概述"), _module$exports);