var _module$exports;

function _defineProperty(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, {
            value: value,
            enumerable: true,
            configurable: true,
            writable: true
        });
    } else {
        obj[key] = value;
    }
    return obj;
}

module.exports = (_module$exports = {
    urlNotInDomainList: "不在request合法域名列表中，請到微信公眾號平臺-登錄小程序賬戶密碼-進入小程序後臺-開發-開發設置-服務器域名",
    requestFailTimeout: "請求超時",
    caozuochenggong: "操作成功",
    chakanzuoping: "查看作品",
    xitongguanggao: "系統廣告",
    an: "按",
    tao: "套",
    zhuangxiugongdi: "裝修工地",
    ge: "個",
    xiaoqu: "小區",
    gegongdi: "個工地",
    jieduan: "階段",
    fangxing: "房型",
    myxggd: "沒有相關工地",
    mygdl: "沒有更多了",
    shangpingshoucang: "商品收藏",
    tupianshoucang: "圖片收藏",
    gongdishoucang: "工地收藏",
    chanpingshoucang: "產品收藏",
    quanjingtushoucang: "全景圖收藏",
    wodedingdan: "我的訂單",
    wodedizhi: "我的地址",
    wodeyouhuiquan: "我的優惠券",
    wodeyuyue: "我的預約",
    lianxikefu: "聯系客服",
    qingchuhuancun: "清除緩存",
    taotu: "套圖",
    dantu: "單圖",
    quanjingtu: "全景圖",
    shousuo: "搜索",
    zonghepaixu: "綜合排序",
    buxian: "不限",
    anshoucangliang: "按收藏量",
    anliulanliang: "按瀏覽量",
    liulan: "瀏覽",
    gengduo: "更多",
    shangpingsousuo: "商品搜索",
    remenxuangou: "熱門選購",
    quxiao: "取消",
    shewei: "設為",
    tianjiadizhi: "添加地址",
    daoruweixindizhi: "導入微信地址",
    xingming: "姓名",
    shoujihao: "手機號",
    diqu: "地區",
    qingxuanzediqu: "請選擇地區",
    xiangxidizhi: "詳細地址",
    sheweimoren: "設為默認"
}, _defineProperty(_module$exports, "tianjiadizhi", "添加地址"), _defineProperty(_module$exports, "baocunxiugai", "保存修改"), 
_defineProperty(_module$exports, "hqzxgj", "獲取裝修報價"), _defineProperty(_module$exports, "fxwxhy", "分享微信好友"), 
_defineProperty(_module$exports, "ndzxys", "妳的裝修預算"), _defineProperty(_module$exports, "yuan", "元"), 
_defineProperty(_module$exports, "srfwmj", "請輸入房屋面積"), _defineProperty(_module$exports, "shuruhaoma", "輸入號碼,報價自動發送"), 
_defineProperty(_module$exports, "huoqushoujihao", "獲取手機號"), _defineProperty(_module$exports, "lijijisuan", "立即計算"), 
_defineProperty(_module$exports, "txxxhqmffuwu", "填寫信息獲取免費服務,定制更精準預算規劃"), _defineProperty(_module$exports, "yixuan", "已選"), 
_defineProperty(_module$exports, "zanwugaishu", "暫無概述"), _defineProperty(_module$exports, "zanwucanshu", "暫無參數"), 
_defineProperty(_module$exports, "yi", "已"), _defineProperty(_module$exports, "shoucang", "收藏"), 
_defineProperty(_module$exports, "gouwuche", "購物車"), _defineProperty(_module$exports, "jiarugouwuche", "加入購物車"), 
_defineProperty(_module$exports, "lijigoumai", "立即購買"), _defineProperty(_module$exports, "guanbi", "關閉"), 
_defineProperty(_module$exports, "renzheng", "認證"), _defineProperty(_module$exports, "anli", "案例"), 
_defineProperty(_module$exports, "gongdi", "工地"), _defineProperty(_module$exports, "tesefuwu", "特色服務"), 
_defineProperty(_module$exports, "zhuangxiuanli", "裝修案例"), _defineProperty(_module$exports, "gong", "共"), 
_defineProperty(_module$exports, "shejituandui", "設計團隊"), _defineProperty(_module$exports, "ren", "人"), 
_defineProperty(_module$exports, "nian", "年經驗"), _defineProperty(_module$exports, "gongyizhanshi", "工藝展示"), 
_defineProperty(_module$exports, "gengduo", "更多"), _defineProperty(_module$exports, "shigongtuandui", "施工團隊"), 
_defineProperty(_module$exports, "shangjiaxinxi", "商家信息"), _defineProperty(_module$exports, "chengjieleixing", "承接類型"), 
_defineProperty(_module$exports, "zwszcjlx", "暫未設置承接類型"), _defineProperty(_module$exports, "chengjiejiawei", "承接價位"), 
_defineProperty(_module$exports, "zwszcjjw", "暫未設置承接價位"), _defineProperty(_module$exports, "fuwuquyu", "服務區域"), 
_defineProperty(_module$exports, "zwszfwq", "暫未設置服務區域"), _defineProperty(_module$exports, "shiyong", "使用"), 
_defineProperty(_module$exports, "qushiyong", "去使用"), _defineProperty(_module$exports, "weishengxiao", "未生效"), 
_defineProperty(_module$exports, "bsyyhq", "不使用優惠券"), _defineProperty(_module$exports, "yilingqu", "已領取"), 
_defineProperty(_module$exports, "lingqu", "領取"), _defineProperty(_module$exports, "yilingwan", "已領完"), 
_defineProperty(_module$exports, "dangquanxuanze", "當前選擇"), _defineProperty(_module$exports, "qsrzxgsmc", "請輸入裝修公司名稱"), 
_defineProperty(_module$exports, "shuaixuan", "篩選"), _defineProperty(_module$exports, "xingyong", "信用"), 
_defineProperty(_module$exports, "jvli", "距離"), _defineProperty(_module$exports, "zonghe", "綜合"), 
_defineProperty(_module$exports, "quyu", "區域"), _defineProperty(_module$exports, "quanbu", "全部"), 
_defineProperty(_module$exports, "leixing", "類型"), _defineProperty(_module$exports, "fengge", "風格"), 
_defineProperty(_module$exports, "yusuan", "預算"), _defineProperty(_module$exports, "qingkong", "清空"), 
_defineProperty(_module$exports, "queren", "確認"), _defineProperty(_module$exports, "quan", "券"), 
_defineProperty(_module$exports, "cu", "促"), _defineProperty(_module$exports, "wang", "萬"), 
_defineProperty(_module$exports, "weiguanfenxi", "圍觀粉絲"), _defineProperty(_module$exports, "shigongliucheng", "施工流程"), 
_defineProperty(_module$exports, "quxiaoshoucang", "取消收藏"), _defineProperty(_module$exports, "nindexingming", "您的姓名"), 
_defineProperty(_module$exports, "nindedianhua", "您的電話"), _defineProperty(_module$exports, "mindeneirong", "您的內容"), 
_defineProperty(_module$exports, "zaixianliuyan", "在線留言"), _defineProperty(_module$exports, "xyndsq", "需要您的授權"), 
_defineProperty(_module$exports, "wltgghdfw", "為了提供更好的服務"), _defineProperty(_module$exports, "qzshdtskzdjyx", "請在稍後的提示框中點擊“允許”"), 
_defineProperty(_module$exports, "wozhidaole", "我知道了"), _defineProperty(_module$exports, "myxgxx", "沒有相關信息"), 
_defineProperty(_module$exports, "dianhuazixun", "電話咨詢"), _defineProperty(_module$exports, "zuopinganli", "作品案例"), 
_defineProperty(_module$exports, "qxzdz", "請選擇地址"), _defineProperty(_module$exports, "qxzyhq", "請選擇優惠券"), 
_defineProperty(_module$exports, "youhuiquan", "優惠券"), _defineProperty(_module$exports, "weixuanze", "未選擇"), 
_defineProperty(_module$exports, "shangpingheji", "商品合計"), _defineProperty(_module$exports, "youhui", "優惠"), 
_defineProperty(_module$exports, "lijixiadan", "立即下單"), _defineProperty(_module$exports, "lijizhifu", "立即支付"), 
_defineProperty(_module$exports, "dingdanhao", "訂單號"), _defineProperty(_module$exports, "chuangjianshijian", "創建時間"), 
_defineProperty(_module$exports, "shangpingheji", "商品合計"), _defineProperty(_module$exports, "syyhq", "使用優惠券"), 
_defineProperty(_module$exports, "youhuijinge", "優惠金額"), _defineProperty(_module$exports, "zhifue", "支付額"), 
_defineProperty(_module$exports, "fenxianghaoyou", "分享好友"), _defineProperty(_module$exports, "weixinhaoyou", "微信好友"), 
_defineProperty(_module$exports, "fenxianghaibao", "分享海報"), _defineProperty(_module$exports, "baocunhaibao", "保存海報"), 
_defineProperty(_module$exports, "qushouquan", "去授權"), _defineProperty(_module$exports, "yuyuejinge", "預約金額"), 
_defineProperty(_module$exports, "mashangyuyue", "馬上預約"), _defineProperty(_module$exports, "sousuo", "搜索"), 
_defineProperty(_module$exports, "myxgtp", "沒有相關圖片"), _defineProperty(_module$exports, "tijiao", "提交"), 
_defineProperty(_module$exports, "zhifujinge", "支付金額"), _defineProperty(_module$exports, "mpmzxygj", "毛坯房裝修預估價"), 
_defineProperty(_module$exports, "wanyuan", "萬元"), _defineProperty(_module$exports, "xhzxgjjhdnmfzx", "稍後裝修管家將回電您,免費提供裝修咨詢服務"), 
_defineProperty(_module$exports, "yclppjgclbtwz", "因材料品牌及工程量不同,具體報價以量房實測為準"), _defineProperty(_module$exports, "wsyxxx", "完善以下信息"), 
_defineProperty(_module$exports, "rwmgljndjtxqyxfw", "讓我們更了解您的具體需求,優先為您服務"), _defineProperty(_module$exports, "njdzxlxs", "您家的裝修類型是"), 
_defineProperty(_module$exports, "jiazhuang", "家裝"), _defineProperty(_module$exports, "gongzhuang", "公裝"), 
_defineProperty(_module$exports, "bangongshi", "辦公室"), _defineProperty(_module$exports, "cantingdeng", "餐廳等"), 
_defineProperty(_module$exports, "njdfwzts", "您家的房屋狀態是"), _defineProperty(_module$exports, "esffxfy", "二手翻新會比毛坯房多部分分拆改費用"), 
_defineProperty(_module$exports, "maopeifang", "毛坯房"), _defineProperty(_module$exports, "jiufangfanxin", "舊房翻新"), 
_defineProperty(_module$exports, "jvbugaizao", "局部改造"), _defineProperty(_module$exports, "njzbssshkszx", "您家準備什麽時候開始裝修"), 
_defineProperty(_module$exports, "bangeyuenei", "半個月內"), _defineProperty(_module$exports, "yigeyuenei", "壹個月內"), 
_defineProperty(_module$exports, "lianggeyuenei", "兩個月內"), _defineProperty(_module$exports, "linaggeyueyishang", "兩個月以上"), 
_defineProperty(_module$exports, "ninjiadeloupan", "您家的樓盤"), _defineProperty(_module$exports, "txlpxxwnyzsg", "填寫樓盤信息,將為您家附近的優質施工方"), 
_defineProperty(_module$exports, "qsrnjdlp", "請輸入您家的樓盤、小區"), _defineProperty(_module$exports, "lijitijiao", "立即提交"), 
_defineProperty(_module$exports, "xiangshangping", "項商品"), _defineProperty(_module$exports, "qufukuan", "去付款"), 
_defineProperty(_module$exports, "dianhua", "電話"), _defineProperty(_module$exports, "meiyouxinxi", "沒有信息"), 
_defineProperty(_module$exports, "shouye", "首頁"), _defineProperty(_module$exports, "fenlei", "分類"), 
_defineProperty(_module$exports, "gouwuche", "購物車"), _defineProperty(_module$exports, "dqxtpzcc", "讀取系統配置出錯！"), 
_defineProperty(_module$exports, "nhdwsskb", "您好，我可以帶妳快速跳轉頁面，點我試試看吧！"), _defineProperty(_module$exports, "yifuzhi", "已復制"), 
_defineProperty(_module$exports, "zhaobudaoidw", "找不到ID為"), _defineProperty(_module$exports, "yzxcx", "預置小程序"), 
_defineProperty(_module$exports, "dyzxcx", "的預置小程序"), _defineProperty(_module$exports, "dappidwx", "的appID無效"), 
_defineProperty(_module$exports, "dappidbz", "的appID不在配置列表中"), _defineProperty(_module$exports, "zbdym", "找不到頁面"), 
_defineProperty(_module$exports, "wzdz", "未知動作"), _defineProperty(_module$exports, "zanwu", "暫無"), 
_defineProperty(_module$exports, "qxqqwsz", "權限，請前往設置開啟"), _defineProperty(_module$exports, "qwsz", "前往設置"), 
_defineProperty(_module$exports, "kucun", "庫存"), _defineProperty(_module$exports, "gmsl", "購買數量"), 
_defineProperty(_module$exports, "qclsjl", "清除歷史紀錄"), _defineProperty(_module$exports, "jiesuan", "結算"), 
_defineProperty(_module$exports, "gwckkry", "購物車空空如也~"), _defineProperty(_module$exports, "msgg", "馬上逛逛"), 
_defineProperty(_module$exports, "daifukuan", "待付款"), _defineProperty(_module$exports, "daifahuo", "待發貨"), 
_defineProperty(_module$exports, "daishouhuo", "待收貨"), _defineProperty(_module$exports, "yiwancheng", "已完成"), 
_defineProperty(_module$exports, "yituikuan", "已退款"), _defineProperty(_module$exports, "myclddo", "還沒有此類訂單哦~"), 
_defineProperty(_module$exports, "chongshi", "重試"), _defineProperty(_module$exports, "mykydyhq", "沒有可用的優惠券"), 
_defineProperty(_module$exports, "weishiyong", "未使用"), _defineProperty(_module$exports, "yishixiao", "已失效"), 
_defineProperty(_module$exports, "nhmyclyhq", "您還沒有此類優惠券"), _defineProperty(_module$exports, "tjbf", "條件不符"), 
_defineProperty(_module$exports, "yishiyong", "已使用"), _defineProperty(_module$exports, "yiguoqi", "已過期"), 
_defineProperty(_module$exports, "nhmyscgspo", "您還沒有收藏過商品哦"), _defineProperty(_module$exports, "hsygg", "回首頁逛逛"), 
_defineProperty(_module$exports, "canshu", "參數"), _defineProperty(_module$exports, "gaishu", "概述"), 
_module$exports);